version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_URL=http://localhost:15121/api/v1
    ports:
      - "15120:80"
    depends_on:
      - backend 
    networks:
      - app-network
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:15121/api/v1}

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "15121:8000"
    env_file:
      - .env
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - LOG_LEVEL=INFO
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-password123}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 