version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: hr_documents_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - hr_network

  mongo-express:
    image: mongo-express:latest
    container_name: hr_documents_mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - hr_network

volumes:
  mongodb_data:
    name: hr_documents_mongodb_data

networks:
  hr_network:
    name: hr_documents_network
