# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Go To Backend
      run: cd ./backend

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        coverage run -m pytest

    - name: Report with coverage.py
      run: |
        coverage report -m > report.txt

    - name: Upload coverage test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-coverage-results-3.12
        path: report.txt
      if: ${{ always() }}
