# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        working-directory: ./backend
        env: 
          ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          coverage run -m pytest .

      - name: Report with coverage.py
        working-directory: ./backend
        run: |
          coverage report -m > report.txt
          coverage xml

      - name: Upload coverage test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage-results-${{ matrix.os }}-${{ github.run_id }}
          path: backend/report.txt
        if: ${{ always() }}

      - name: Upload coverage to Codecov
        working-directory: ./backend
        uses: codecov/codecov-action@v5
        with:
          directory: ./
          env_vars: OS,PYTHON_VERSION
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true