# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Test with pytest
      working-directory: ./backend
      env: 
        ANTHROPIC_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        
      run: |
        python -m pytest app/tests/ -v --tb=short

    - name: Report with coverage.py
      working-directory: ./backend
      run: |
        coverage run -m pytest app/tests/
        coverage report -m > report.txt
        coverage xml

    - name: Upload coverage test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-coverage-results-${{ matrix.os }}-${{ github.run_id }}
        path: backend/report.txt
      if: ${{ always() }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        directory: ./backend
        env_vars: OS,PYTHON-VERSION
        fail_ci_if_error: true
        files: ./backend/coverage.xml
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true